Fix for TUSCANY-1731. Excluded xerces from axiom-api dependencies, and replaced by a dependency on xerces 2.8.1. Added a dependency on xml-api 1.3.03 instead to have this level instead of 1.0.b2. This fixes NoSuchMethodError and VerifyError exceptions when running on WebSphere.
git-svn-id: https://svn.apache.org/repos/asf/incubator/tuscany/branches/sca-java-1.0@576709 13f79535-47bb-0310-9956-ffa450edef68